### ISSUE TITLE
aten-us421a control protocol

### ISSUE THREAD

**Issue by sjorge** [hmaerki/usb_switches#1]
I'm looking for a cheap 2 -> 1 remote controllable usb switch too and found this repo while looking around.
I also found https://github.com/kellpete/US421A-Switcher/blob/master/US421A-Switcher/PeripheralSwitchUs421a.cpp, is probbaly usable to help understand the protocol used to control the device.

Hopefully it's useful for you.

**Comment by hmaerki** [comment]
Hi Jorge
Thanks a lot for the link!
I added links to software here https://github.com/hmaerki/usb_switches/tree/master/it-well_IT-102AU_USB2 and https://github.com/hmaerki/usb_switches/tree/master/it-well_IT-204MU_USB2/usb_controlled.
This could be helpful for you.

**Comment by sjorge** [comment]
Thanks for the extra links! I got both one of the cheap ali express ones and the ATEN on the way.
The design of the ali express is certainly more appealing though.

**Comment by sjorge** [comment]
Couldn't get reading to work yet, but switch, lock and unlock seem to work fine. Tested on freebsd but it uses libusb and py-hidapi, so it should work on linux too.

```python
#!/usr/bin/python
# require py-hidapi

import hid
from time import sleep

class ATENUsbSwitch(object):
    def __init__(self, vendor_id=1367, product_id=9223):
        self.dev = hid.device()
        self.dev.open(vendor_id, product_id)

    def switch(self):
        self.dev.write([0x02, 0x11])

    def lock(self):
        self.dev.write([0x02, 0x11])

    def unlock(self):
        self.dev.write([0x02, 0x20])

    def keep_locked(self):
        self.lock()
        while True:
            sleep(4)
            self.dev.write([0x02, 0x40])

    def status(self):
        # XXX: unimplemented
        pass

    def __del__(self):
        self.dev.close()

if __name__ == "__main__":
    usbsw = ATENUsbSwitch()
    #usbsw.switch()
    usbsw.status()
```

**Comment by sjorge** [comment]
Here is a more fleshed out version that queries the status too:

```
root@fermion:~ # usbconfig list
ugen0.1: <0x1912 XHCI root HUB> at usbus0, cfg=0 md=HOST spd=SUPER (5.0Gbps) pwr=SAVE (0mA)
ugen0.2: <USB 2.0 Peripheral Switch USB 2.0 Peripheral Switch> at usbus0, cfg=0 md=HOST spd=FULL (12Mbps) pwr=ON (200mA)
root@fermion:~ # python atenusbsw.py
Switching device ... Done!
root@fermion:~ # usbconfig list
ugen0.1: <0x1912 XHCI root HUB> at usbus0, cfg=0 md=HOST spd=SUPER (5.0Gbps) pwr=SAVE (0mA)
ugen0.2: <vendor 0x1a40 USB 2.0 Hub> at usbus0, cfg=0 md=HOST spd=HIGH (480Mbps) pwr=SAVE (100mA)
ugen0.3: <Realtek 802.11n WLAN Adapter> at usbus0, cfg=0 md=HOST spd=HIGH (480Mbps) pwr=ON (500mA)
ugen0.4: <USB 2.0 Peripheral Switch USB 2.0 Peripheral Switch> at usbus0, cfg=0 md=HOST spd=FULL (12Mbps) pwr=ON (200mA)
```

https://github.com/sjorge/aten-us221a-switcher/blob/main/atenusbsw.py
